#- name: Install the correct web server for RHEL
#  import_tasks: redhat.yml
#  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'


- name: Include the example role
  include_role:
    name: common
#
#- name: Install the correct web server for centos
#  import_tasks: centos.yml
#  when: ansible_facts['os_family']|lower == 'centos'