---
- name: host machine
  hosts: all
  become: true
  vars_files:
  - usernames
  tasks:
  - name: Add several users
    ansible.builtin.user:
     name: "{{ item }}"
     state: present
     groups: "wheel"
    loop: "{{ users }}"
...