---
- hosts: web
  become: true

  tasks:
  - name: install httpd on servers
    ansibile.builtin.yum:
      name=httpd
      state=present
  - name: start the http service
    ansible.builtin.service:
      name=httpd
      state=started
  - name: copy the index html to destination
    ansible.builtin.copy:
        dest: /var/www/html/index.html
        src: /opt/index.html
...